apiServer:
  host: "0.0.0.0" # Change to a specific host if needed
  port: 3000
  plugins:
    - packageName: "@hyperledger/cactus-plugin-ledger-connector-ethereum"
      options:
        rpcApiHttpHost: "https://sepolia.infura.io/v3/YOUR_INFURA_PROJECT_ID"
        instanceId: "ethereum-connector"
    - packageName: "@hyperledger/cactus-plugin-ledger-connector-fabric"
      options:
        connectionProfile: "/root/Blockchain/foundry-23/foundry-simple-storage-23/fabric/fabric-network/connection-org1.json"
        fabricWalletDir: "/root/Blockchain/foundry-23/foundry-simple-storage-23/fabric/wallet"
        identity: "admin"
        channelName: "mychannel"
        chaincodeId: "c6dc790944117516873392a7cf7103088d253aea4ff65c0f56099cce1aa097d6"
